//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceTest.OJService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblemDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ProblemDO : PerformanceTest.OJService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DefunctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescribeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DifficultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fg_specialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HintField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime In_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Memory_limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sample_inputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sample_outputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SolvedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SubmitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Time_limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UploaderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Accepted {
            get {
                return this.AcceptedField;
            }
            set {
                if ((this.AcceptedField.Equals(value) != true)) {
                    this.AcceptedField = value;
                    this.RaisePropertyChanged("Accepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Defunct {
            get {
                return this.DefunctField;
            }
            set {
                if ((this.DefunctField.Equals(value) != true)) {
                    this.DefunctField = value;
                    this.RaisePropertyChanged("Defunct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Describe {
            get {
                return this.DescribeField;
            }
            set {
                if ((object.ReferenceEquals(this.DescribeField, value) != true)) {
                    this.DescribeField = value;
                    this.RaisePropertyChanged("Describe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Difficulty {
            get {
                return this.DifficultyField;
            }
            set {
                if ((object.ReferenceEquals(this.DifficultyField, value) != true)) {
                    this.DifficultyField = value;
                    this.RaisePropertyChanged("Difficulty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fg_special {
            get {
                return this.Fg_specialField;
            }
            set {
                if ((object.ReferenceEquals(this.Fg_specialField, value) != true)) {
                    this.Fg_specialField = value;
                    this.RaisePropertyChanged("Fg_special");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hint {
            get {
                return this.HintField;
            }
            set {
                if ((object.ReferenceEquals(this.HintField, value) != true)) {
                    this.HintField = value;
                    this.RaisePropertyChanged("Hint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime In_date {
            get {
                return this.In_dateField;
            }
            set {
                if ((this.In_dateField.Equals(value) != true)) {
                    this.In_dateField = value;
                    this.RaisePropertyChanged("In_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input {
            get {
                return this.InputField;
            }
            set {
                if ((object.ReferenceEquals(this.InputField, value) != true)) {
                    this.InputField = value;
                    this.RaisePropertyChanged("Input");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Memory_limit {
            get {
                return this.Memory_limitField;
            }
            set {
                if ((this.Memory_limitField.Equals(value) != true)) {
                    this.Memory_limitField = value;
                    this.RaisePropertyChanged("Memory_limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Output {
            get {
                return this.OutputField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputField, value) != true)) {
                    this.OutputField = value;
                    this.RaisePropertyChanged("Output");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sample_input {
            get {
                return this.Sample_inputField;
            }
            set {
                if ((object.ReferenceEquals(this.Sample_inputField, value) != true)) {
                    this.Sample_inputField = value;
                    this.RaisePropertyChanged("Sample_input");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sample_output {
            get {
                return this.Sample_outputField;
            }
            set {
                if ((object.ReferenceEquals(this.Sample_outputField, value) != true)) {
                    this.Sample_outputField = value;
                    this.RaisePropertyChanged("Sample_output");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Solved {
            get {
                return this.SolvedField;
            }
            set {
                if ((this.SolvedField.Equals(value) != true)) {
                    this.SolvedField = value;
                    this.RaisePropertyChanged("Solved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Submit {
            get {
                return this.SubmitField;
            }
            set {
                if ((this.SubmitField.Equals(value) != true)) {
                    this.SubmitField = value;
                    this.RaisePropertyChanged("Submit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Time_limit {
            get {
                return this.Time_limitField;
            }
            set {
                if ((this.Time_limitField.Equals(value) != true)) {
                    this.Time_limitField = value;
                    this.RaisePropertyChanged("Time_limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Uploader {
            get {
                return this.UploaderField;
            }
            set {
                if ((this.UploaderField.Equals(value) != true)) {
                    this.UploaderField = value;
                    this.RaisePropertyChanged("Uploader");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SolutionDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.LanguageDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SourceCodeDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.UserDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.ProblemDO))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SolutionDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.LanguageDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SourceCodeDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.UserDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.ProblemDO))]
    public partial class EntityObject : PerformanceTest.OJService.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolutionDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SolutionDO : PerformanceTest.OJService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeLenghtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTimeOffset> createTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_contestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_problemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> judgeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.LanguageDO languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.EntityReferenceOfLanguageDOUWpDsVqM languageReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> memoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass_rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.SourceCodeDO sourcecodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.EntityReferenceOfSourceCodeDOUWpDsVqM sourcecodeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> validField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codeLenght {
            get {
                return this.codeLenghtField;
            }
            set {
                if ((object.ReferenceEquals(this.codeLenghtField, value) != true)) {
                    this.codeLenghtField = value;
                    this.RaisePropertyChanged("codeLenght");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTimeOffset> createTime {
            get {
                return this.createTimeField;
            }
            set {
                if ((this.createTimeField.Equals(value) != true)) {
                    this.createTimeField = value;
                    this.RaisePropertyChanged("createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_contest {
            get {
                return this.id_contestField;
            }
            set {
                if ((object.ReferenceEquals(this.id_contestField, value) != true)) {
                    this.id_contestField = value;
                    this.RaisePropertyChanged("id_contest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_language {
            get {
                return this.id_languageField;
            }
            set {
                if ((this.id_languageField.Equals(value) != true)) {
                    this.id_languageField = value;
                    this.RaisePropertyChanged("id_language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_problem {
            get {
                return this.id_problemField;
            }
            set {
                if ((this.id_problemField.Equals(value) != true)) {
                    this.id_problemField = value;
                    this.RaisePropertyChanged("id_problem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> judgeTime {
            get {
                return this.judgeTimeField;
            }
            set {
                if ((this.judgeTimeField.Equals(value) != true)) {
                    this.judgeTimeField = value;
                    this.RaisePropertyChanged("judgeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.LanguageDO language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.EntityReferenceOfLanguageDOUWpDsVqM languageReference {
            get {
                return this.languageReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.languageReferenceField, value) != true)) {
                    this.languageReferenceField = value;
                    this.RaisePropertyChanged("languageReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> memory {
            get {
                return this.memoryField;
            }
            set {
                if ((this.memoryField.Equals(value) != true)) {
                    this.memoryField = value;
                    this.RaisePropertyChanged("memory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> num {
            get {
                return this.numField;
            }
            set {
                if ((this.numField.Equals(value) != true)) {
                    this.numField = value;
                    this.RaisePropertyChanged("num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass_rate {
            get {
                return this.pass_rateField;
            }
            set {
                if ((object.ReferenceEquals(this.pass_rateField, value) != true)) {
                    this.pass_rateField = value;
                    this.RaisePropertyChanged("pass_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.SourceCodeDO sourcecode {
            get {
                return this.sourcecodeField;
            }
            set {
                if ((object.ReferenceEquals(this.sourcecodeField, value) != true)) {
                    this.sourcecodeField = value;
                    this.RaisePropertyChanged("sourcecode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.EntityReferenceOfSourceCodeDOUWpDsVqM sourcecodeReference {
            get {
                return this.sourcecodeReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.sourcecodeReferenceField, value) != true)) {
                    this.sourcecodeReferenceField = value;
                    this.RaisePropertyChanged("sourcecodeReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userIp {
            get {
                return this.userIpField;
            }
            set {
                if ((object.ReferenceEquals(this.userIpField, value) != true)) {
                    this.userIpField = value;
                    this.RaisePropertyChanged("userIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> valid {
            get {
                return this.validField;
            }
            set {
                if ((this.validField.Equals(value) != true)) {
                    this.validField = value;
                    this.RaisePropertyChanged("valid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LanguageDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class LanguageDO : PerformanceTest.OJService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceCodeDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SourceCodeDO : PerformanceTest.OJService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Id_solutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Source_codeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id_solution {
            get {
                return this.Id_solutionField;
            }
            set {
                if ((this.Id_solutionField.Equals(value) != true)) {
                    this.Id_solutionField = value;
                    this.RaisePropertyChanged("Id_solution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source_code {
            get {
                return this.Source_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Source_codeField, value) != true)) {
                    this.Source_codeField = value;
                    this.RaisePropertyChanged("Source_code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserDO : PerformanceTest.OJService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AccessTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DefunctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SolvedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SubmitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessIp {
            get {
                return this.AccessIpField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessIpField, value) != true)) {
                    this.AccessIpField = value;
                    this.RaisePropertyChanged("AccessIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AccessTime {
            get {
                return this.AccessTimeField;
            }
            set {
                if ((this.AccessTimeField.Equals(value) != true)) {
                    this.AccessTimeField = value;
                    this.RaisePropertyChanged("AccessTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Defunct {
            get {
                return this.DefunctField;
            }
            set {
                if ((this.DefunctField.Equals(value) != true)) {
                    this.DefunctField = value;
                    this.RaisePropertyChanged("Defunct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_language {
            get {
                return this.Id_languageField;
            }
            set {
                if ((this.Id_languageField.Equals(value) != true)) {
                    this.Id_languageField = value;
                    this.RaisePropertyChanged("Id_language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegIp {
            get {
                return this.RegIpField;
            }
            set {
                if ((object.ReferenceEquals(this.RegIpField, value) != true)) {
                    this.RegIpField = value;
                    this.RaisePropertyChanged("RegIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegTime {
            get {
                return this.RegTimeField;
            }
            set {
                if ((this.RegTimeField.Equals(value) != true)) {
                    this.RegTimeField = value;
                    this.RaisePropertyChanged("RegTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string School {
            get {
                return this.SchoolField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolField, value) != true)) {
                    this.SchoolField = value;
                    this.RaisePropertyChanged("School");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Solved {
            get {
                return this.SolvedField;
            }
            set {
                if ((this.SolvedField.Equals(value) != true)) {
                    this.SolvedField = value;
                    this.RaisePropertyChanged("Solved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Submit {
            get {
                return this.SubmitField;
            }
            set {
                if ((this.SubmitField.Equals(value) != true)) {
                    this.SubmitField = value;
                    this.RaisePropertyChanged("Submit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityReferenceOfLanguageDOUWpDsVqM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityReferenceOfSourceCodeDOUWpDsVqM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.DateTimeOffset))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.ProblemPageList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.PageListOfProblemDOUWpDsVqM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SolutionPageList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.PageListOfSolutionDOUWpDsVqM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.UserPageList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.PageListOfUserDOUWpDsVqM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.ProblemDO[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.ProblemDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SolutionDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.LanguageDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SourceCodeDO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SolutionDO[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.UserDO[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.UserDO))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfLanguageDOUWpDsVqM", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfLanguageDOUWpDsVqM : PerformanceTest.OJService.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityReferenceOfSourceCodeDOUWpDsVqM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityReferenceOfLanguageDOUWpDsVqM))]
    public partial class EntityReference : PerformanceTest.OJService.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityReferenceOfSourceCodeDOUWpDsVqM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.EntityReferenceOfLanguageDOUWpDsVqM))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfSourceCodeDOUWpDsVqM", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfSourceCodeDOUWpDsVqM : PerformanceTest.OJService.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblemPageList", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    public partial class ProblemPageList : PerformanceTest.OJService.PageListOfProblemDOUWpDsVqM {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageListOfProblemDOUWpDsVqM", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.ProblemPageList))]
    public partial class PageListOfProblemDOUWpDsVqM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.ProblemDO[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.ProblemDO[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolutionPageList", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    public partial class SolutionPageList : PerformanceTest.OJService.PageListOfSolutionDOUWpDsVqM {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageListOfSolutionDOUWpDsVqM", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.SolutionPageList))]
    public partial class PageListOfSolutionDOUWpDsVqM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.SolutionDO[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.SolutionDO[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPageList", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    public partial class UserPageList : PerformanceTest.OJService.PageListOfUserDOUWpDsVqM {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageListOfUserDOUWpDsVqM", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PerformanceTest.OJService.UserPageList))]
    public partial class PageListOfUserDOUWpDsVqM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PerformanceTest.OJService.UserDO[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PerformanceTest.OJService.UserDO[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OJService.IOJService")]
    public interface IOJService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/AfreshJudge", ReplyAction="http://tempuri.org/IOJService/AfreshJudgeResponse")]
        void AfreshJudge();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/Test", ReplyAction="http://tempuri.org/IOJService/TestResponse")]
        string Test(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetProblemList", ReplyAction="http://tempuri.org/IOJService/GetProblemListResponse")]
        PerformanceTest.OJService.ProblemDO[] GetProblemList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetProblemPageList", ReplyAction="http://tempuri.org/IOJService/GetProblemPageListResponse")]
        PerformanceTest.OJService.ProblemPageList GetProblemPageList(int pageSize, int pageIndex, string queryText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetProblemById", ReplyAction="http://tempuri.org/IOJService/GetProblemByIdResponse")]
        PerformanceTest.OJService.ProblemDO GetProblemById(long problemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/AddProblem", ReplyAction="http://tempuri.org/IOJService/AddProblemResponse")]
        PerformanceTest.OJService.ProblemDO AddProblem(PerformanceTest.OJService.ProblemDO problem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/UpdateProblem", ReplyAction="http://tempuri.org/IOJService/UpdateProblemResponse")]
        PerformanceTest.OJService.ProblemDO UpdateProblem(PerformanceTest.OJService.ProblemDO problem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/DeleleProblemById", ReplyAction="http://tempuri.org/IOJService/DeleleProblemByIdResponse")]
        bool DeleleProblemById(long problemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/DeleleProblem", ReplyAction="http://tempuri.org/IOJService/DeleleProblemResponse")]
        bool DeleleProblem(PerformanceTest.OJService.ProblemDO problem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/SubmitCode", ReplyAction="http://tempuri.org/IOJService/SubmitCodeResponse")]
        PerformanceTest.OJService.SolutionDO SubmitCode(long problem, string language, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/SubmitJudgeResult", ReplyAction="http://tempuri.org/IOJService/SubmitJudgeResultResponse")]
        bool SubmitJudgeResult(PerformanceTest.OJService.SolutionDO solution);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetSolutionPageList", ReplyAction="http://tempuri.org/IOJService/GetSolutionPageListResponse")]
        PerformanceTest.OJService.SolutionPageList GetSolutionPageList(int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetUserDoByUserName", ReplyAction="http://tempuri.org/IOJService/GetUserDoByUserNameResponse")]
        PerformanceTest.OJService.UserDO[] GetUserDoByUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetUserPageList", ReplyAction="http://tempuri.org/IOJService/GetUserPageListResponse")]
        PerformanceTest.OJService.UserPageList GetUserPageList(int pageSize, int pageIndex, string queryText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetUserById", ReplyAction="http://tempuri.org/IOJService/GetUserByIdResponse")]
        PerformanceTest.OJService.UserDO GetUserById(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/AddUser", ReplyAction="http://tempuri.org/IOJService/AddUserResponse")]
        string AddUser(string userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/AddUserDo", ReplyAction="http://tempuri.org/IOJService/AddUserDoResponse")]
        bool AddUserDo(PerformanceTest.OJService.UserDO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/UpdateUser", ReplyAction="http://tempuri.org/IOJService/UpdateUserResponse")]
        bool UpdateUser(PerformanceTest.OJService.UserDO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/DeleteUserById", ReplyAction="http://tempuri.org/IOJService/DeleteUserByIdResponse")]
        bool DeleteUserById(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOJServiceChannel : PerformanceTest.OJService.IOJService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OJServiceClient : System.ServiceModel.ClientBase<PerformanceTest.OJService.IOJService>, PerformanceTest.OJService.IOJService {
        
        public OJServiceClient() {
        }
        
        public OJServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OJServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OJServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OJServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AfreshJudge() {
            base.Channel.AfreshJudge();
        }
        
        public string Test(string str) {
            return base.Channel.Test(str);
        }
        
        public PerformanceTest.OJService.ProblemDO[] GetProblemList() {
            return base.Channel.GetProblemList();
        }
        
        public PerformanceTest.OJService.ProblemPageList GetProblemPageList(int pageSize, int pageIndex, string queryText) {
            return base.Channel.GetProblemPageList(pageSize, pageIndex, queryText);
        }
        
        public PerformanceTest.OJService.ProblemDO GetProblemById(long problemId) {
            return base.Channel.GetProblemById(problemId);
        }
        
        public PerformanceTest.OJService.ProblemDO AddProblem(PerformanceTest.OJService.ProblemDO problem) {
            return base.Channel.AddProblem(problem);
        }
        
        public PerformanceTest.OJService.ProblemDO UpdateProblem(PerformanceTest.OJService.ProblemDO problem) {
            return base.Channel.UpdateProblem(problem);
        }
        
        public bool DeleleProblemById(long problemId) {
            return base.Channel.DeleleProblemById(problemId);
        }
        
        public bool DeleleProblem(PerformanceTest.OJService.ProblemDO problem) {
            return base.Channel.DeleleProblem(problem);
        }
        
        public PerformanceTest.OJService.SolutionDO SubmitCode(long problem, string language, string code) {
            return base.Channel.SubmitCode(problem, language, code);
        }
        
        public bool SubmitJudgeResult(PerformanceTest.OJService.SolutionDO solution) {
            return base.Channel.SubmitJudgeResult(solution);
        }
        
        public PerformanceTest.OJService.SolutionPageList GetSolutionPageList(int pageSize, int pageIndex) {
            return base.Channel.GetSolutionPageList(pageSize, pageIndex);
        }
        
        public PerformanceTest.OJService.UserDO[] GetUserDoByUserName(string userName) {
            return base.Channel.GetUserDoByUserName(userName);
        }
        
        public PerformanceTest.OJService.UserPageList GetUserPageList(int pageSize, int pageIndex, string queryText) {
            return base.Channel.GetUserPageList(pageSize, pageIndex, queryText);
        }
        
        public PerformanceTest.OJService.UserDO GetUserById(int userId) {
            return base.Channel.GetUserById(userId);
        }
        
        public string AddUser(string userInfo) {
            return base.Channel.AddUser(userInfo);
        }
        
        public bool AddUserDo(PerformanceTest.OJService.UserDO user) {
            return base.Channel.AddUserDo(user);
        }
        
        public bool UpdateUser(PerformanceTest.OJService.UserDO user) {
            return base.Channel.UpdateUser(user);
        }
        
        public bool DeleteUserById(int userId) {
            return base.Channel.DeleteUserById(userId);
        }
    }
}
