//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcftest.OJService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblemDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ProblemDO : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DefunctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescribeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DifficultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fg_specialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HintField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime In_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Memory_limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sample_inputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sample_outputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SolvedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SubmitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Time_limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UploaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Accepted {
            get {
                return this.AcceptedField;
            }
            set {
                this.AcceptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Defunct {
            get {
                return this.DefunctField;
            }
            set {
                this.DefunctField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Describe {
            get {
                return this.DescribeField;
            }
            set {
                this.DescribeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Difficulty {
            get {
                return this.DifficultyField;
            }
            set {
                this.DifficultyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fg_special {
            get {
                return this.Fg_specialField;
            }
            set {
                this.Fg_specialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hint {
            get {
                return this.HintField;
            }
            set {
                this.HintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime In_date {
            get {
                return this.In_dateField;
            }
            set {
                this.In_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input {
            get {
                return this.InputField;
            }
            set {
                this.InputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Memory_limit {
            get {
                return this.Memory_limitField;
            }
            set {
                this.Memory_limitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Output {
            get {
                return this.OutputField;
            }
            set {
                this.OutputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sample_input {
            get {
                return this.Sample_inputField;
            }
            set {
                this.Sample_inputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sample_output {
            get {
                return this.Sample_outputField;
            }
            set {
                this.Sample_outputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Solved {
            get {
                return this.SolvedField;
            }
            set {
                this.SolvedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Submit {
            get {
                return this.SubmitField;
            }
            set {
                this.SubmitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Time_limit {
            get {
                return this.Time_limitField;
            }
            set {
                this.Time_limitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Uploader {
            get {
                return this.UploaderField;
            }
            set {
                this.UploaderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolutionDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SolutionDO : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeLenghtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTimeOffset> createTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_contestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_problemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> judgeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wcftest.OJService.LanguageDO languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<wcftest.OJService.LanguageDO> languageReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> memoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass_rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wcftest.OJService.SourceCodeDO sourcecodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<wcftest.OJService.SourceCodeDO> sourcecodeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> validField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codeLenght {
            get {
                return this.codeLenghtField;
            }
            set {
                this.codeLenghtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTimeOffset> createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_contest {
            get {
                return this.id_contestField;
            }
            set {
                this.id_contestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_language {
            get {
                return this.id_languageField;
            }
            set {
                this.id_languageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_problem {
            get {
                return this.id_problemField;
            }
            set {
                this.id_problemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_user {
            get {
                return this.id_userField;
            }
            set {
                this.id_userField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> judgeTime {
            get {
                return this.judgeTimeField;
            }
            set {
                this.judgeTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcftest.OJService.LanguageDO language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<wcftest.OJService.LanguageDO> languageReference {
            get {
                return this.languageReferenceField;
            }
            set {
                this.languageReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> memory {
            get {
                return this.memoryField;
            }
            set {
                this.memoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass_rate {
            get {
                return this.pass_rateField;
            }
            set {
                this.pass_rateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcftest.OJService.SourceCodeDO sourcecode {
            get {
                return this.sourcecodeField;
            }
            set {
                this.sourcecodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<wcftest.OJService.SourceCodeDO> sourcecodeReference {
            get {
                return this.sourcecodeReferenceField;
            }
            set {
                this.sourcecodeReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userIp {
            get {
                return this.userIpField;
            }
            set {
                this.userIpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LanguageDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class LanguageDO : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceCodeDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SourceCodeDO : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Id_solutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Source_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id_solution {
            get {
                return this.Id_solutionField;
            }
            set {
                this.Id_solutionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source_code {
            get {
                return this.Source_codeField;
            }
            set {
                this.Source_codeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDO", Namespace="http://schemas.datacontract.org/2004/07/OJ.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserDO : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AccessTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DefunctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SolvedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SubmitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessIp {
            get {
                return this.AccessIpField;
            }
            set {
                this.AccessIpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AccessTime {
            get {
                return this.AccessTimeField;
            }
            set {
                this.AccessTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                this.BirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Defunct {
            get {
                return this.DefunctField;
            }
            set {
                this.DefunctField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_language {
            get {
                return this.Id_languageField;
            }
            set {
                this.Id_languageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegIp {
            get {
                return this.RegIpField;
            }
            set {
                this.RegIpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegTime {
            get {
                return this.RegTimeField;
            }
            set {
                this.RegTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string School {
            get {
                return this.SchoolField;
            }
            set {
                this.SchoolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Solved {
            get {
                return this.SolvedField;
            }
            set {
                this.SolvedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Submit {
            get {
                return this.SubmitField;
            }
            set {
                this.SubmitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageListOfProblemDOUWpDsVqM", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcftest.OJService.ProblemPageList))]
    public partial class PageListOfProblemDOUWpDsVqM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wcftest.OJService.ProblemDO[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcftest.OJService.ProblemDO[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblemPageList", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    public partial class ProblemPageList : wcftest.OJService.PageListOfProblemDOUWpDsVqM {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageListOfSolutionDOUWpDsVqM", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcftest.OJService.SolutionPageList))]
    public partial class PageListOfSolutionDOUWpDsVqM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wcftest.OJService.SolutionDO[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcftest.OJService.SolutionDO[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolutionPageList", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    public partial class SolutionPageList : wcftest.OJService.PageListOfSolutionDOUWpDsVqM {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageListOfUserDOUWpDsVqM", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcftest.OJService.UserPageList))]
    public partial class PageListOfUserDOUWpDsVqM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wcftest.OJService.UserDO[] DataListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcftest.OJService.UserDO[] DataList {
            get {
                return this.DataListField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListField, value) != true)) {
                    this.DataListField = value;
                    this.RaisePropertyChanged("DataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPageList", Namespace="http://schemas.datacontract.org/2004/07/OJ.BLL.PageList")]
    [System.SerializableAttribute()]
    public partial class UserPageList : wcftest.OJService.PageListOfUserDOUWpDsVqM {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OJService.IOJService")]
    public interface IOJService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/AfreshJudge", ReplyAction="http://tempuri.org/IOJService/AfreshJudgeResponse")]
        void AfreshJudge();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/Test", ReplyAction="http://tempuri.org/IOJService/TestResponse")]
        string Test(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetProblemList", ReplyAction="http://tempuri.org/IOJService/GetProblemListResponse")]
        wcftest.OJService.ProblemDO[] GetProblemList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetProblemPageList", ReplyAction="http://tempuri.org/IOJService/GetProblemPageListResponse")]
        wcftest.OJService.ProblemPageList GetProblemPageList(int pageSize, int pageIndex, string queryText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetProblemById", ReplyAction="http://tempuri.org/IOJService/GetProblemByIdResponse")]
        wcftest.OJService.ProblemDO GetProblemById(long problemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/AddProblem", ReplyAction="http://tempuri.org/IOJService/AddProblemResponse")]
        wcftest.OJService.ProblemDO AddProblem(wcftest.OJService.ProblemDO problem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/UpdateProblem", ReplyAction="http://tempuri.org/IOJService/UpdateProblemResponse")]
        wcftest.OJService.ProblemDO UpdateProblem(wcftest.OJService.ProblemDO problem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/DeleleProblemById", ReplyAction="http://tempuri.org/IOJService/DeleleProblemByIdResponse")]
        bool DeleleProblemById(long problemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/DeleleProblem", ReplyAction="http://tempuri.org/IOJService/DeleleProblemResponse")]
        bool DeleleProblem(wcftest.OJService.ProblemDO problem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/SubmitCode", ReplyAction="http://tempuri.org/IOJService/SubmitCodeResponse")]
        wcftest.OJService.SolutionDO SubmitCode(long problem, string language, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/SubmitJudgeResult", ReplyAction="http://tempuri.org/IOJService/SubmitJudgeResultResponse")]
        bool SubmitJudgeResult(wcftest.OJService.SolutionDO solution);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetSolutionPageList", ReplyAction="http://tempuri.org/IOJService/GetSolutionPageListResponse")]
        wcftest.OJService.SolutionPageList GetSolutionPageList(int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetUserDoByUserName", ReplyAction="http://tempuri.org/IOJService/GetUserDoByUserNameResponse")]
        wcftest.OJService.UserDO[] GetUserDoByUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetUserPageList", ReplyAction="http://tempuri.org/IOJService/GetUserPageListResponse")]
        wcftest.OJService.UserPageList GetUserPageList(int pageSize, int pageIndex, string queryText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/GetUserById", ReplyAction="http://tempuri.org/IOJService/GetUserByIdResponse")]
        wcftest.OJService.UserDO GetUserById(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/AddUser", ReplyAction="http://tempuri.org/IOJService/AddUserResponse")]
        string AddUser(string userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/AddUserDo", ReplyAction="http://tempuri.org/IOJService/AddUserDoResponse")]
        bool AddUserDo(wcftest.OJService.UserDO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/UpdateUser", ReplyAction="http://tempuri.org/IOJService/UpdateUserResponse")]
        bool UpdateUser(wcftest.OJService.UserDO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOJService/DeleteUserById", ReplyAction="http://tempuri.org/IOJService/DeleteUserByIdResponse")]
        bool DeleteUserById(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOJServiceChannel : wcftest.OJService.IOJService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OJServiceClient : System.ServiceModel.ClientBase<wcftest.OJService.IOJService>, wcftest.OJService.IOJService {
        
        public OJServiceClient() {
        }
        
        public OJServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OJServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OJServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OJServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AfreshJudge() {
            base.Channel.AfreshJudge();
        }
        
        public string Test(string str) {
            return base.Channel.Test(str);
        }
        
        public wcftest.OJService.ProblemDO[] GetProblemList() {
            return base.Channel.GetProblemList();
        }
        
        public wcftest.OJService.ProblemPageList GetProblemPageList(int pageSize, int pageIndex, string queryText) {
            return base.Channel.GetProblemPageList(pageSize, pageIndex, queryText);
        }
        
        public wcftest.OJService.ProblemDO GetProblemById(long problemId) {
            return base.Channel.GetProblemById(problemId);
        }
        
        public wcftest.OJService.ProblemDO AddProblem(wcftest.OJService.ProblemDO problem) {
            return base.Channel.AddProblem(problem);
        }
        
        public wcftest.OJService.ProblemDO UpdateProblem(wcftest.OJService.ProblemDO problem) {
            return base.Channel.UpdateProblem(problem);
        }
        
        public bool DeleleProblemById(long problemId) {
            return base.Channel.DeleleProblemById(problemId);
        }
        
        public bool DeleleProblem(wcftest.OJService.ProblemDO problem) {
            return base.Channel.DeleleProblem(problem);
        }
        
        public wcftest.OJService.SolutionDO SubmitCode(long problem, string language, string code) {
            return base.Channel.SubmitCode(problem, language, code);
        }
        
        public bool SubmitJudgeResult(wcftest.OJService.SolutionDO solution) {
            return base.Channel.SubmitJudgeResult(solution);
        }
        
        public wcftest.OJService.SolutionPageList GetSolutionPageList(int pageSize, int pageIndex) {
            return base.Channel.GetSolutionPageList(pageSize, pageIndex);
        }
        
        public wcftest.OJService.UserDO[] GetUserDoByUserName(string userName) {
            return base.Channel.GetUserDoByUserName(userName);
        }
        
        public wcftest.OJService.UserPageList GetUserPageList(int pageSize, int pageIndex, string queryText) {
            return base.Channel.GetUserPageList(pageSize, pageIndex, queryText);
        }
        
        public wcftest.OJService.UserDO GetUserById(int userId) {
            return base.Channel.GetUserById(userId);
        }
        
        public string AddUser(string userInfo) {
            return base.Channel.AddUser(userInfo);
        }
        
        public bool AddUserDo(wcftest.OJService.UserDO user) {
            return base.Channel.AddUserDo(user);
        }
        
        public bool UpdateUser(wcftest.OJService.UserDO user) {
            return base.Channel.UpdateUser(user);
        }
        
        public bool DeleteUserById(int userId) {
            return base.Channel.DeleteUserById(userId);
        }
    }
}
