//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJService.JudgeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JudgeService.IJudgeEnginesService")]
    public interface IJudgeEnginesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJudgeEnginesService/DoWork", ReplyAction="http://tempuri.org/IJudgeEnginesService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJudgeEnginesService/AddSolution", ReplyAction="http://tempuri.org/IJudgeEnginesService/AddSolutionResponse")]
        bool AddSolution(OJ.Domain.SolutionDO solution);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJudgeEnginesServiceChannel : IJudgeEnginesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JudgeEnginesServiceClient : System.ServiceModel.ClientBase<IJudgeEnginesService>, IJudgeEnginesService {
        
        public JudgeEnginesServiceClient() {
        }
        
        public JudgeEnginesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JudgeEnginesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JudgeEnginesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JudgeEnginesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public bool AddSolution(OJ.Domain.SolutionDO solution) {
            return base.Channel.AddSolution(solution);
        }
    }
}
